# a sample config file for use with models included in this repo
model_name: spacenet4_baseline
model_arch: ternausnetv1
framework: keras
model_src:
train: true
infer: true

datagen:
  batch_size: 4
  crop: true
  resize: false
  output_x: 512
  output_y: 512
  augmentation:
    flip_x: true
    flip_y: true
    rotate: [0, 90, 180, 270]


data:
  ###################################
  ### TRAINING DATA SPECIFICATION ###
  ###################################

  # Path to source imagery for training.
  train_im_src_dirs:
    -
  # path to labels (masks).
  train_label_src_dirs:
    -
  # next two denote paths to val data.
  val_im_src_dirs:
    -
  val_label_src_dirs:
    -
  ###################################
  ### INFERENCE DATA SPECIFICATION ##
  ###################################
  # path to source imagery for inference.
  infer_im_src_dirs:
    -


output:
  # path to save model after training.
  model_dest:
  model_save: [best, final]  # alternative value: all (save every checkpoint)
  model_checkpoint: # epochs to checkpoint at (optional)
  # path to save predictions (INFERENCE ONLY)
  pred_dest:

training:
  pretrained: true
  epochs: 1000
  loss: hybrid_bce_jaccard
  optimizer: Nadam
  lr: 0.0002
  early_stopping:
    patience: 15
    monitor: val_loss
  reduce_lr_on_plateau:
    patience: 3
    factor: 0.2
